version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Nothing to do here...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - Dockerfile
